### ISSUE TITLE
Göra Json

### ISSUE THREAD

**Issue by antonpetersson** [antonpetersson/RSVP#6]

**Comment by antonpetersson** [comment]
Info att ha med i "bilden":

    Datum, tid

    Namn

    beskrivning
    -bild

**Comment by andremedie** [comment]
inte glömma bort att antingen lägga till en fjärde fest med bild, gäster, starttid osv. Eventuellt att ta bort den fjärde platsen..

**Comment by andremedie** [comment]
Detalj...: 
Lägga till i .json filen Vart nånstans är festen?
